### ISSUE TITLE
Prim's Algorithm

### ISSUE THREAD

**Issue by aniketpatil03** [aniketpatil03/Hacktoberfest2020#7]
You have a business with several offices; you want to lease phone lines to connect them up with each other, and the phone company charges different amounts of money to connect different pairs of cities. You want a set of lines that connects all your offices with a minimum total cost. Solve the problem by suggesting appropriate data structures.

**Comment by AbhishekJambure** [comment]
Hii... I can solve this.

**Comment by aniketpatil03** [comment]
You got it
